version: '3'
services:
  calculator_frontend:
    image: calculator_frontend:latest
    environment:
      PORT: 3000
      REACT_APP_PROXY_API: http://localhost
    ports:
      - 3000:3000
  calculator_backend:
    image: calculator_backend:latest
    ports:
      - 8080:8080